"""Top-level learning domains and their publication state."""
from __future__ import annotations

DOMAINS = [
    {
        "id": "data-foundations",
        "title_en": "Data Foundations",
        "title_bn": "ডেটা ফাউন্ডেশন",
        "description_en": "Build data literacy, analytical thinking, data quality awareness and a reliable problem-solving workflow.",
        "description_bn": "Data literacy, analytical thinking, data quality awareness ও নির্ভরযোগ্য problem-solving workflow তৈরি করুন।",
        "status": "tutorial-published",
        "release": "v2.1.0",
        "icon": "database",
        "accent": "violet",
        "module_ids": ["foundations", "analytics"],
        "url": "/tutorials/data-foundations/",
    },
    {
        "id": "statistics",
        "title_en": "Statistics for Analytics",
        "title_bn": "অ্যানালিটিক্সের জন্য স্ট্যাটিস্টিকস",
        "description_en": "Use descriptive statistics, probability, inference and regression to interpret evidence responsibly.",
        "description_bn": "Descriptive statistics, probability, inference ও regression দিয়ে evidence দায়িত্বশীলভাবে ব্যাখ্যা করুন।",
        "status": "available",
        "release": "v2.0.0",
        "icon": "sigma",
        "accent": "cyan",
        "module_ids": ["descriptive", "probability", "inference", "regression", "advanced"],
        "url": "/learn/?domain=statistics",
    },
    {
        "id": "excel",
        "title_en": "Excel for Data Analytics",
        "title_bn": "ডেটা অ্যানালিটিক্সের জন্য Excel",
        "description_en": "Clean, calculate, summarize and communicate data with formulas, tables, PivotTables, Power Query and dashboards.",
        "description_bn": "Formula, table, PivotTable, Power Query ও dashboard দিয়ে data clean, calculate, summarize ও communicate করুন।",
        "status": "tutorial-published",
        "release": "v2.2.0",
        "icon": "sheet",
        "accent": "emerald",
        "module_ids": [],
        "url": "/tutorials/excel-data-analytics/",
    },
    {
        "id": "sql",
        "title_en": "SQL for Data Analytics",
        "title_bn": "ডেটা অ্যানালিটিক্সের জন্য SQL",
        "description_en": "Query, combine and analyze relational data from filtering and aggregation through window functions and analytical patterns.",
        "description_bn": "Filtering ও aggregation থেকে window function এবং analytical pattern পর্যন্ত relational data query ও analyze করুন।",
        "status": "tutorial-published",
        "release": "v2.3.0",
        "icon": "terminal",
        "accent": "blue",
        "module_ids": [],
        "url": "/tutorials/sql-data-analytics/",
    },
    {
        "id": "power-bi",
        "title_en": "Power BI for Data Analytics",
        "title_bn": "ডেটা অ্যানালিটিক্সের জন্য Power BI",
        "description_en": "Prepare data, build semantic models, write DAX and create accessible decision-ready reports.",
        "description_bn": "Data prepare, semantic model build, DAX লিখে accessible decision-ready report তৈরি করুন।",
        "status": "tutorial-published",
        "release": "v2.4.0",
        "icon": "dashboard",
        "accent": "amber",
        "module_ids": [],
        "url": "/tutorials/power-bi-data-analytics/",
    },
    {
        "id": "python",
        "title_en": "Python for Data Analytics",
        "title_bn": "ডেটা অ্যানালিটিক্সের জন্য Python",
        "description_en": "Use Python, pandas and Matplotlib to clean, explore, analyze and communicate reproducible findings.",
        "description_bn": "Python, pandas ও Matplotlib দিয়ে reproducible data cleaning, exploration, analysis ও communication করুন।",
        "status": "curriculum-ready",
        "release": "v2.5.0",
        "icon": "code",
        "accent": "indigo",
        "module_ids": [],
        "url": "/curriculum/#python",
    },
    {
        "id": "projects",
        "title_en": "Projects & Portfolio",
        "title_bn": "প্রজেক্ট ও পোর্টফোলিও",
        "description_en": "Integrate the same business datasets across statistics, Excel, SQL, Power BI and Python.",
        "description_bn": "একই business dataset-কে statistics, Excel, SQL, Power BI ও Python-এ integrate করুন।",
        "status": "foundation-ready",
        "release": "v2.0.0 → v2.6.0",
        "icon": "briefcase",
        "accent": "pink",
        "module_ids": [],
        "url": "/projects/",
    },
    {
        "id": "data-science",
        "title_en": "Data Science",
        "title_bn": "ডেটা সায়েন্স",
        "description_en": "A future advanced path building on analytics, statistics and Python foundations.",
        "description_bn": "Analytics, statistics ও Python foundation-এর ওপর ভবিষ্যৎ advanced path।",
        "status": "roadmap",
        "release": "v3.0.0",
        "icon": "brain",
        "accent": "orange",
        "module_ids": ["data-science"],
        "url": "/career-paths/#data-scientist",
    },
    {
        "id": "data-engineering",
        "title_en": "Data Engineering",
        "title_bn": "ডেটা ইঞ্জিনিয়ারিং",
        "description_en": "A future advanced path building on SQL, Python, modeling and data-quality foundations.",
        "description_bn": "SQL, Python, modeling ও data-quality foundation-এর ওপর ভবিষ্যৎ advanced path।",
        "status": "roadmap",
        "release": "v4.0.0",
        "icon": "pipeline",
        "accent": "teal",
        "module_ids": ["data-engineering"],
        "url": "/career-paths/#data-engineer",
    },
]
