"""Bilingual cross-domain glossary entries."""
from __future__ import annotations

GLOSSARY = [('Accuracy',
  'অ্যাকিউরেসি',
  'The proportion of all predictions that are correct.',
  'সব prediction-এর মধ্যে সঠিক prediction-এর অনুপাত।'),
 ('Alternative hypothesis',
  'অল্টারনেটিভ হাইপোথিসিস',
  'The claim considered when evidence is inconsistent with the null hypothesis.',
  'null hypothesis-এর সঙ্গে evidence অসামঞ্জস্য হলে যে claim বিবেচনা করা হয়।'),
 ('Bias',
  'বায়াস',
  'A systematic tendency for an estimate or process to differ from the target.',
  'কোনো estimate বা process-এর target থেকে পদ্ধতিগতভাবে সরে যাওয়ার প্রবণতা।'),
 ('Categorical variable',
  'ক্যাটেগরিক্যাল ভেরিয়েবল',
  'A variable whose values represent groups or labels.',
  'যে ভেরিয়েবলের মান group বা label প্রকাশ করে।'),
 ('Central limit theorem',
  'সেন্ট্রাল লিমিট থিওরেম',
  'A result describing when standardized sample means are approximately normal.',
  'কখন standardized sample mean প্রায় normal হয় তা ব্যাখ্যা করা ফলাফল।'),
 ('Confidence interval',
  'কনফিডেন্স ইন্টারভ্যাল',
  'A procedure that produces a range of plausible parameter values at a stated confidence level.',
  'নির্দিষ্ট confidence level-এ plausible parameter value-এর range তৈরির procedure।'),
 ('Confounder',
  'কনফাউন্ডার',
  'A variable related to both an exposure and an outcome that can distort their association.',
  'exposure ও outcome উভয়ের সঙ্গে সম্পর্কিত variable, যা তাদের association বিকৃত করতে পারে।'),
 ('Correlation',
  'কোরিলেশন',
  'A standardized measure of association; it does not by itself establish causation.',
  'association-এর standardized measure; এটি নিজে causation প্রমাণ করে না।'),
 ('Covariance',
  'কোভ্যারিয়েন্স',
  'A measure of how two variables vary together, expressed in product units.',
  'দুই variable একসঙ্গে কীভাবে পরিবর্তিত হয় তার measure, product unit-এ প্রকাশিত।'),
 ('Cross-validation',
  'ক্রস-ভ্যালিডেশন',
  'A resampling method for estimating out-of-sample model performance.',
  'out-of-sample model performance অনুমানের resampling method।'),
 ('Data lineage',
  'ডেটা লিনিয়েজ',
  'A record of where data came from, how it changed, and where it is used.',
  'ডেটা কোথা থেকে এসেছে, কীভাবে বদলেছে এবং কোথায় ব্যবহৃত হয়েছে তার রেকর্ড।'),
 ('Distribution',
  'ডিস্ট্রিবিউশন',
  'The pattern of possible values and their frequencies or probabilities.',
  'সম্ভাব্য মান এবং তাদের frequency বা probability-এর pattern।'),
 ('Effect size',
  'ইফেক্ট সাইজ',
  'A quantitative measure of the magnitude of a difference or relationship.',
  'difference বা relationship-এর magnitude-এর quantitative measure।'),
 ('ELT',
  'ELT',
  'Extract, load, then transform data inside the target analytical system.',
  'ডেটা extract ও load করার পর target analytical system-এর ভেতরে transform করা।'),
 ('ETL',
  'ETL',
  'Extract, transform, then load data into a target system.',
  'ডেটা extract, transform এবং পরে target system-এ load করা।'),
 ('Expected value',
  'এক্সপেক্টেড ভ্যালু',
  'The probability-weighted long-run average of a random variable.',
  'random variable-এর probability-weighted long-run average।'),
 ('Feature',
  'ফিচার',
  'An input variable used by an analytical or machine-learning model.',
  'analytical বা machine-learning model-এ ব্যবহৃত input variable।'),
 ('Hypothesis test',
  'হাইপোথিসিস টেস্ট',
  'A rule-based procedure for evaluating evidence about a population claim.',
  'population claim সম্পর্কে evidence মূল্যায়নের rule-based procedure।'),
 ('Interquartile range',
  'ইন্টারকোয়ার্টাইল রেঞ্জ',
  'Q3 minus Q1; the spread of the middle 50% of observations.',
  'Q3 − Q1; মাঝের ৫০% observation-এর spread।'),
 ('Mean',
  'মিন',
  'The arithmetic average of numeric observations.',
  'নিউমেরিক observation-এর arithmetic average।'),
 ('Median',
  'মিডিয়ান',
  'The middle value after sorting, or the average of two middle values for even n.',
  'sort করার পর মাঝের মান; even n হলে দুই মাঝের মানের average।'),
 ('Null hypothesis',
  'নাল হাইপোথিসিস',
  'The reference claim tested by a statistical procedure.',
  'statistical procedure দিয়ে test করা reference claim।'),
 ('Outlier',
  'আউটলায়ার',
  'An observation unusually far from the main body of data; it is not automatically an error.',
  'ডেটার মূল অংশ থেকে অস্বাভাবিক দূরের observation; এটি স্বয়ংক্রিয়ভাবে error নয়।'),
 ('p-value',
  'পি-ভ্যালু',
  'Under the null model, the probability of a result at least as incompatible with the null as the observed '
  'result.',
  'null model সত্য ধরে observed result-এর মতো বা তার চেয়ে বেশি incompatible result পাওয়ার probability।'),
 ('Parameter',
  'প্যারামিটার',
  'A fixed but usually unknown numerical characteristic of a population or model.',
  'population বা model-এর fixed কিন্তু সাধারণত unknown numerical characteristic।'),
 ('Population',
  'পপুলেশন',
  'The complete set of units or outcomes targeted by an analysis.',
  'analysis যে সম্পূর্ণ set of units বা outcomes-কে target করে।'),
 ('Precision',
  'প্রিসিশন',
  'For classification, the proportion of positive predictions that are truly positive.',
  'classification-এ positive prediction-এর মধ্যে সত্যিকারের positive-এর অনুপাত।'),
 ('Probability',
  'প্রবাবিলিটি',
  'A number from 0 to 1 representing uncertainty under a specified model.',
  'নির্দিষ্ট model-এ uncertainty প্রকাশকারী ০ থেকে ১-এর একটি সংখ্যা।'),
 ('Quantile',
  'কোয়ান্টাইল',
  'A cut point that divides an ordered distribution at a chosen cumulative probability.',
  'ordered distribution-কে নির্দিষ্ট cumulative probability-এ ভাগ করা cut point।'),
 ('R-squared',
  'R-squared',
  'The proportion of outcome variation explained by a fitted regression model relative to a baseline mean '
  'model.',
  'baseline mean model-এর তুলনায় fitted regression model outcome variation-এর যে অনুপাত ব্যাখ্যা করে।'),
 ('Recall',
  'রিকল',
  'The proportion of actual positive cases correctly identified.',
  'actual positive case-এর মধ্যে সঠিকভাবে শনাক্ত positive-এর অনুপাত।'),
 ('Regression',
  'রিগ্রেশন',
  'A family of models for describing conditional relationships between outcomes and predictors.',
  'outcome ও predictor-এর conditional relationship বর্ণনার model family।'),
 ('Residual',
  'রেসিডুয়াল',
  "Observed outcome minus the model's fitted value.",
  'observed outcome − model-এর fitted value।'),
 ('Sample',
  'স্যাম্পল',
  'A subset of units observed from a target population.',
  'target population থেকে observed unit-এর subset।'),
 ('Sampling distribution',
  'স্যাম্পলিং ডিস্ট্রিবিউশন',
  'The distribution of a statistic across repeated samples under a sampling process.',
  'sampling process-এ repeated sample জুড়ে একটি statistic-এর distribution।'),
 ('Standard deviation',
  'স্ট্যান্ডার্ড ডেভিয়েশন',
  'The square root of variance, expressed in the original measurement unit.',
  'variance-এর square root, original measurement unit-এ প্রকাশিত।'),
 ('Standard error',
  'স্ট্যান্ডার্ড এরর',
  "The standard deviation of an estimator's sampling distribution.",
  'একটি estimator-এর sampling distribution-এর standard deviation।'),
 ('Statistic',
  'স্ট্যাটিস্টিক',
  'A numerical summary calculated from sample data.',
  'sample data থেকে হিসাব করা numerical summary।'),
 ('Variance',
  'ভ্যারিয়েন্স',
  'The average squared deviation from a mean, with population or sample conventions.',
  'mean থেকে squared deviation-এর average, population বা sample convention অনুযায়ী।'),
 ('Warehouse',
  'ডেটা ওয়্যারহাউস',
  'A managed analytical store optimized for structured querying and reporting.',
  'structured query ও reporting-এর জন্য optimized managed analytical store।')]
