"""v1 learning paths retained for progress migration and reference."""
from __future__ import annotations

PATHS = [{'id': 'statistics-foundations',
  'title_en': 'Statistics Foundations Path',
  'title_bn': 'স্ট্যাটিস্টিকস ফাউন্ডেশন পাথ',
  'description_en': 'A calm, concept-first route through data literacy, descriptive statistics, probability, '
                    'inference, relationships, and responsible interpretation.',
  'description_bn': 'ডেটা লিটারেসি, descriptive statistics, probability, inference, relationship ও '
                    'responsible interpretation-এর একটি শান্ত concept-first route।',
  'topics': ['statistics-and-data',
             'population-and-sample',
             'variables-and-observations',
             'measurement-scales',
             'categorical-and-numerical-data',
             'sampling-bias-and-confounding',
             'mean-median-and-mode',
             'variance-and-standard-deviation',
             'histograms',
             'normal-distribution',
             'sampling-distributions',
             'confidence-intervals',
             'pearson-and-spearman-correlation',
             'simple-linear-regression',
             'exploratory-data-analysis',
             'data-storytelling']},
 {'id': 'data-analyst',
  'title_en': 'Data Analyst Path',
  'title_bn': 'ডেটা অ্যানালিস্ট পাথ',
  'description_en': 'From data literacy to EDA, inference, regression, business metrics, experiments, and '
                    'storytelling.',
  'description_bn': 'ডেটা লিটারেসি থেকে EDA, inference, regression, business metric, experiment ও '
                    'storytelling পর্যন্ত।',
  'topics': ['statistics-and-data',
             'categorical-and-numerical-data',
             'frequency-tables',
             'mean-median-and-mode',
             'variance-and-standard-deviation',
             'histograms',
             'box-plots',
             'exploratory-data-analysis',
             'confidence-intervals',
             'hypothesis-testing-framework',
             'pearson-and-spearman-correlation',
             'simple-linear-regression',
             'kpi-design',
             'cohort-analysis',
             'funnel-analysis',
             'a-b-testing',
             'moving-averages-and-smoothing',
             'data-storytelling']},
 {'id': 'data-scientist',
  'title_en': 'Data Scientist Path',
  'title_bn': 'ডেটা সায়েন্টিস্ট পাথ',
  'description_en': 'Probability, inference, modeling, resampling, feature preparation, clustering, Bayesian '
                    'and causal reasoning.',
  'description_bn': 'probability, inference, modeling, resampling, feature preparation, clustering, Bayesian '
                    'ও causal reasoning।',
  'topics': ['probability-rules',
             'conditional-probability',
             'random-variables',
             'normal-distribution',
             'central-limit-theorem',
             'confidence-intervals',
             'type-i-type-ii-errors-and-power',
             'simple-linear-regression',
             'multiple-linear-regression',
             'logistic-regression',
             'model-validation',
             'bootstrap',
             'cross-validation',
             'bias-variance-trade-off',
             'feature-engineering',
             'principal-component-analysis',
             'k-means-clustering',
             'classification-metrics',
             'bayesian-inference',
             'causal-inference']},
 {'id': 'data-engineer',
  'title_en': 'Data Engineer Path',
  'title_bn': 'ডেটা ইঞ্জিনিয়ার পাথ',
  'description_en': 'Build statistical literacy, then focus on data modeling, SQL, transformations, quality, '
                    'orchestration, lineage, and semantic layers.',
  'description_bn': 'statistical literacy তৈরি করে data modeling, SQL, transformation, quality, '
                    'orchestration, lineage ও semantic layer-এ এগিয়ে যান।',
  'topics': ['statistics-and-data',
             'data-quality-dimensions',
             'reproducible-statistical-workflow',
             'data-formats-csv-json-and-parquet',
             'relational-data-modeling',
             'sql-for-analytics',
             'normalization-and-denormalization',
             'etl-and-elt',
             'batch-and-streaming-data',
             'warehouse-lake-and-lakehouse',
             'dimensional-modeling-and-star-schemas',
             'data-quality-testing',
             'pipeline-orchestration',
             'data-lineage-and-governance',
             'analytics-engineering-and-semantic-layers']},
 {'id': 'research-business',
  'title_en': 'Research & Business Decision Path',
  'title_bn': 'রিসার্চ ও বিজনেস ডিসিশন পাথ',
  'description_en': 'Sampling, measurement, uncertainty, experiments, group comparisons, regression, '
                    'forecasting, and defensible communication.',
  'description_bn': 'sampling, measurement, uncertainty, experiment, group comparison, regression, '
                    'forecasting ও defensible communication।',
  'topics': ['population-and-sample',
             'measurement-scales',
             'data-collection-methods',
             'probability-and-non-probability-sampling',
             'sampling-bias-and-confounding',
             'exploratory-data-analysis-workflow',
             'confidence-intervals',
             'hypothesis-testing-framework',
             'tests-for-proportions',
             'chi-square-tests',
             'analysis-of-variance',
             'simple-linear-regression',
             'a-b-testing',
             'forecast-evaluation',
             'data-storytelling',
             'experimental-design',
             'causal-inference']}]
