"""Stable v1.2.0 statistics curriculum migrated into the v2 content architecture."""
from __future__ import annotations

MODULES = [{'id': 'foundations',
  'title_en': 'Data & Statistics Foundations',
  'title_bn': 'ডেটা ও পরিসংখ্যানের ভিত্তি',
  'description_en': 'Build the vocabulary, data literacy, sampling awareness, and workflow habits needed '
                    'before formal analysis.',
  'description_bn': 'আনুষ্ঠানিক বিশ্লেষণের আগে প্রয়োজনীয় পরিভাষা, ডেটা লিটারেসি, স্যাম্পলিং ধারণা ও সুশৃঙ্খল '
                    'কাজের ধারা তৈরি করুন।',
  'accent': 'violet',
  'icon': 'database',
  'topics': [('Statistics and Data', 'পরিসংখ্যান ও ডেটা', 'Beginner', 'lesson'),
             ('Population and Sample', 'পপুলেশন ও স্যাম্পল', 'Beginner', 'lesson'),
             ('Variables and Observations', 'ভেরিয়েবল ও অবজারভেশন', 'Beginner', 'lesson'),
             ('Measurement Scales', 'পরিমাপের স্কেল', 'Beginner', 'lesson'),
             ('Categorical and Numerical Data', 'ক্যাটেগরিক্যাল ও নিউমেরিক্যাল ডেটা', 'Beginner', 'lesson'),
             ('Data Collection Methods', 'ডেটা সংগ্রহের পদ্ধতি', 'Beginner', 'lesson'),
             ('Probability and Non-probability Sampling',
              'প্রবাবিলিটি ও নন-প্রবাবিলিটি স্যাম্পলিং',
              'Intermediate',
              'lesson'),
             ('Sampling Bias and Confounding', 'স্যাম্পলিং বায়াস ও কনফাউন্ডিং', 'Intermediate', 'lesson'),
             ('Data Quality Dimensions', 'ডেটা কোয়ালিটির মাত্রা', 'Intermediate', 'lesson'),
             ('Frequency Tables', 'ফ্রিকোয়েন্সি টেবিল', 'Beginner', 'practice'),
             ('Exploratory Data Analysis Workflow',
              'এক্সপ্লোরেটরি ডেটা অ্যানালাইসিস ওয়ার্কফ্লো',
              'Intermediate',
              'practice'),
             ('Reproducible Statistical Workflow',
              'পুনরুৎপাদনযোগ্য পরিসংখ্যান ওয়ার্কফ্লো',
              'Intermediate',
              'lesson')]},
 {'id': 'descriptive',
  'title_en': 'Descriptive Statistics & Visualization',
  'title_bn': 'বর্ণনামূলক পরিসংখ্যান ও ভিজ্যুয়ালাইজেশন',
  'description_en': 'Summarize distributions, compare groups, detect unusual values, and communicate '
                    'patterns with appropriate charts.',
  'description_bn': 'ডিস্ট্রিবিউশন সংক্ষেপ করুন, গ্রুপ তুলনা করুন, অস্বাভাবিক মান শনাক্ত করুন এবং উপযুক্ত '
                    'চার্টে প্যাটার্ন ব্যাখ্যা করুন।',
  'accent': 'cyan',
  'icon': 'chart',
  'topics': [('Mean, Median and Mode', 'মিন, মিডিয়ান ও মোড', 'Beginner', 'lab', 'summary-statistics'),
             ('Weighted, Geometric and Harmonic Means',
              'ওয়েটেড, জ্যামিতিক ও হারমোনিক গড়',
              'Intermediate',
              'lab',
              'weighted-mean'),
             ('Quantiles and Percentiles',
              'কোয়ান্টাইল ও পার্সেন্টাইল',
              'Beginner',
              'lab',
              'percentile-quartile'),
             ('Range and Interquartile Range',
              'রেঞ্জ ও ইন্টারকোয়ার্টাইল রেঞ্জ',
              'Beginner',
              'lab',
              'summary-statistics'),
             ('Variance and Standard Deviation',
              'ভ্যারিয়েন্স ও স্ট্যান্ডার্ড ডেভিয়েশন',
              'Beginner',
              'lab',
              'summary-statistics'),
             ('Coefficient of Variation', 'কো-এফিশিয়েন্ট অব ভ্যারিয়েশন', 'Intermediate', 'lesson'),
             ('Skewness', 'স্কিউনেস', 'Intermediate', 'lesson'),
             ('Kurtosis', 'কার্টোসিস', 'Intermediate', 'lesson'),
             ('Outlier Detection', 'আউটলায়ার শনাক্তকরণ', 'Intermediate', 'lab', 'box-plot'),
             ('Histograms', 'হিস্টোগ্রাম', 'Beginner', 'lab', 'histogram'),
             ('Box Plots', 'বক্স প্লট', 'Beginner', 'lab', 'box-plot'),
             ('Scatter, Line and Bar Charts', 'স্ক্যাটার, লাইন ও বার চার্ট', 'Beginner', 'practice')]},
 {'id': 'probability',
  'title_en': 'Probability & Distributions',
  'title_bn': 'প্রবাবিলিটি ও ডিস্ট্রিবিউশন',
  'description_en': 'Model uncertainty with probability rules, random variables, common distributions, '
                    'sampling distributions, and the CLT.',
  'description_bn': 'প্রবাবিলিটি রুল, র\u200d্যান্ডম ভেরিয়েবল, প্রচলিত ডিস্ট্রিবিউশন, স্যাম্পলিং '
                    'ডিস্ট্রিবিউশন ও CLT দিয়ে অনিশ্চয়তা মডেল করুন।',
  'accent': 'blue',
  'icon': 'dice',
  'topics': [('Probability Rules', 'প্রবাবিলিটির নিয়ম', 'Beginner', 'lesson'),
             ('Conditional Probability', 'শর্তাধীন প্রবাবিলিটি', 'Intermediate', 'lesson'),
             ("Bayes' Theorem", 'বেইজের উপপাদ্য', 'Intermediate', 'lesson'),
             ('Random Variables', 'র\u200d্যান্ডম ভেরিয়েবল', 'Beginner', 'lesson'),
             ('Expected Value and Variance', 'এক্সপেক্টেড ভ্যালু ও ভ্যারিয়েন্স', 'Intermediate', 'lesson'),
             ('Bernoulli and Binomial Distributions',
              'বার্নুলি ও বাইনোমিয়াল ডিস্ট্রিবিউশন',
              'Intermediate',
              'lab',
              'binomial-probability'),
             ('Poisson Distribution', 'পয়সন ডিস্ট্রিবিউশন', 'Intermediate', 'lab', 'poisson-probability'),
             ('Uniform Distribution', 'ইউনিফর্ম ডিস্ট্রিবিউশন', 'Beginner', 'lesson'),
             ('Normal Distribution', 'নরমাল ডিস্ট্রিবিউশন', 'Intermediate', 'lab', 'normal-probability'),
             ('Exponential Distribution', 'এক্সপোনেনশিয়াল ডিস্ট্রিবিউশন', 'Intermediate', 'lesson'),
             ('Sampling Distributions', 'স্যাম্পলিং ডিস্ট্রিবিউশন', 'Intermediate', 'lesson'),
             ('Central Limit Theorem', 'সেন্ট্রাল লিমিট থিওরেম', 'Intermediate', 'lab', 'clt-simulator')]},
 {'id': 'inference',
  'title_en': 'Statistical Inference & Experimentation',
  'title_bn': 'স্ট্যাটিস্টিক্যাল ইনফারেন্স ও এক্সপেরিমেন্টেশন',
  'description_en': 'Estimate unknown quantities, test evidence, quantify uncertainty, compare groups, and '
                    'design defensible experiments.',
  'description_bn': 'অজানা প্যারামিটার অনুমান, প্রমাণ যাচাই, অনিশ্চয়তা পরিমাপ, গ্রুপ তুলনা এবং গ্রহণযোগ্য '
                    'এক্সপেরিমেন্ট ডিজাইন শিখুন।',
  'accent': 'emerald',
  'icon': 'flask',
  'topics': [('Point Estimation', 'পয়েন্ট এস্টিমেশন', 'Intermediate', 'lesson'),
             ('Confidence Intervals',
              'কনফিডেন্স ইন্টারভ্যাল',
              'Intermediate',
              'lab',
              'mean-confidence-interval'),
             ('Hypothesis Testing Framework', 'হাইপোথিসিস টেস্টিং ফ্রেমওয়ার্ক', 'Intermediate', 'lesson'),
             ('p-values and Significance Levels',
              'পি-ভ্যালু ও সিগনিফিক্যান্স লেভেল',
              'Intermediate',
              'lesson'),
             ('Type I, Type II Errors and Power', 'টাইপ I, টাইপ II এরর ও পাওয়ার', 'Intermediate', 'lesson'),
             ('One-sample z and t Tests',
              'ওয়ান-স্যাম্পল z ও t টেস্ট',
              'Intermediate',
              'lab',
              'one-sample-t-test'),
             ('Two-sample t Test', 'টু-স্যাম্পল t টেস্ট', 'Intermediate', 'lab', 'two-sample-t-test'),
             ('Paired t Test', 'পেয়ার্ড t টেস্ট', 'Intermediate', 'lesson'),
             ('Tests for Proportions', 'প্রপোরশনের টেস্ট', 'Intermediate', 'lab', 'ab-test'),
             ('Chi-square Tests', 'কাই-স্কয়ার টেস্ট', 'Intermediate', 'lab', 'chi-square-independence'),
             ('Analysis of Variance', 'অ্যানালাইসিস অব ভ্যারিয়েন্স', 'Advanced', 'lesson'),
             ('Nonparametric Tests', 'ননপ্যারামেট্রিক টেস্ট', 'Advanced', 'lesson')]},
 {'id': 'regression',
  'title_en': 'Correlation & Regression Modeling',
  'title_bn': 'কোরিলেশন ও রিগ্রেশন মডেলিং',
  'description_en': 'Measure relationships, build predictive models, diagnose assumptions, and evaluate '
                    'out-of-sample performance.',
  'description_bn': 'সম্পর্ক পরিমাপ, প্রেডিক্টিভ মডেল তৈরি, অ্যাসাম্পশন যাচাই এবং নতুন ডেটায় পারফরম্যান্স '
                    'মূল্যায়ন করুন।',
  'accent': 'orange',
  'icon': 'trend',
  'topics': [('Covariance and Correlation', 'কোভ্যারিয়েন্স ও কোরিলেশন', 'Intermediate', 'lesson'),
             ('Pearson and Spearman Correlation',
              'পিয়ারসন ও স্পিয়ারম্যান কোরিলেশন',
              'Intermediate',
              'lab',
              'pearson-correlation'),
             ('Simple Linear Regression',
              'সিম্পল লিনিয়ার রিগ্রেশন',
              'Intermediate',
              'lab',
              'linear-regression'),
             ('Ordinary Least Squares', 'অর্ডিনারি লিস্ট স্কয়ারস', 'Intermediate', 'lesson'),
             ('R-squared and Adjusted R-squared', 'R-squared ও Adjusted R-squared', 'Intermediate', 'lesson'),
             ('Residual Diagnostics', 'রেসিডুয়াল ডায়াগনস্টিকস', 'Advanced', 'lesson'),
             ('Confidence and Prediction Intervals',
              'কনফিডেন্স ও প্রেডিকশন ইন্টারভ্যাল',
              'Advanced',
              'lesson'),
             ('Multiple Linear Regression', 'মাল্টিপল লিনিয়ার রিগ্রেশন', 'Advanced', 'lesson'),
             ('Multicollinearity and VIF', 'মাল্টিকোলিনিয়ারিটি ও VIF', 'Advanced', 'lesson'),
             ('Logistic Regression', 'লজিস্টিক রিগ্রেশন', 'Advanced', 'lesson'),
             ('Regularization: Ridge and Lasso', 'রেগুলারাইজেশন: রিজ ও লাসো', 'Advanced', 'lesson'),
             ('Model Validation', 'মডেল ভ্যালিডেশন', 'Advanced', 'practice')]},
 {'id': 'analytics',
  'title_en': 'Data Analytics & Business Statistics',
  'title_bn': 'ডেটা অ্যানালিটিক্স ও বিজনেস স্ট্যাটিস্টিকস',
  'description_en': 'Turn raw business data into reliable metrics, experiments, forecasts, and '
                    'decision-ready narratives.',
  'description_bn': 'কাঁচা ব্যবসায়িক ডেটাকে নির্ভরযোগ্য মেট্রিক, এক্সপেরিমেন্ট, ফোরকাস্ট ও সিদ্ধান্তযোগ্য '
                    'গল্পে রূপ দিন।',
  'accent': 'pink',
  'icon': 'briefcase',
  'topics': [('Data Cleaning', 'ডেটা ক্লিনিং', 'Beginner', 'practice'),
             ('Missing Data', 'মিসিং ডেটা', 'Intermediate', 'lesson'),
             ('Outlier Treatment', 'আউটলায়ার ট্রিটমেন্ট', 'Intermediate', 'lesson'),
             ('Exploratory Data Analysis', 'এক্সপ্লোরেটরি ডেটা অ্যানালাইসিস', 'Intermediate', 'practice'),
             ('KPI Design', 'KPI ডিজাইন', 'Intermediate', 'lesson'),
             ('Cohort Analysis', 'কোহর্ট অ্যানালাইসিস', 'Intermediate', 'lesson'),
             ('Funnel Analysis', 'ফানেল অ্যানালাইসিস', 'Intermediate', 'lesson'),
             ('A/B Testing', 'A/B টেস্টিং', 'Intermediate', 'lab', 'ab-test'),
             ('Time-series Components', 'টাইম সিরিজ কম্পোনেন্ট', 'Intermediate', 'lesson'),
             ('Moving Averages and Smoothing',
              'মুভিং এভারেজ ও স্মুথিং',
              'Intermediate',
              'lab',
              'moving-average'),
             ('Forecast Evaluation', 'ফোরকাস্ট মূল্যায়ন', 'Advanced', 'lesson'),
             ('Data Storytelling', 'ডেটা স্টোরিটেলিং', 'Intermediate', 'practice')]},
 {'id': 'data-science',
  'title_en': 'Data Science Statistics',
  'title_bn': 'ডেটা সায়েন্স স্ট্যাটিস্টিকস',
  'description_en': 'Connect statistical reasoning to feature preparation, resampling, unsupervised '
                    'learning, and model evaluation.',
  'description_bn': 'ফিচার প্রস্তুতি, রিস্যাম্পলিং, আনসুপারভাইজড লার্নিং ও মডেল মূল্যায়নের সঙ্গে '
                    'পরিসংখ্যানগত যুক্তি যুক্ত করুন।',
  'accent': 'indigo',
  'icon': 'brain',
  'topics': [('Bootstrap', 'বুটস্ট্র্যাপ', 'Advanced', 'lesson'),
             ('Cross-validation', 'ক্রস-ভ্যালিডেশন', 'Intermediate', 'lesson'),
             ('Bias-Variance Trade-off', 'বায়াস-ভ্যারিয়েন্স ট্রেড-অফ', 'Advanced', 'lesson'),
             ('Feature Engineering', 'ফিচার ইঞ্জিনিয়ারিং', 'Intermediate', 'practice'),
             ('Scaling and Encoding', 'স্কেলিং ও এনকোডিং', 'Intermediate', 'practice'),
             ('Principal Component Analysis', 'প্রিন্সিপাল কম্পোনেন্ট অ্যানালাইসিস', 'Advanced', 'lesson'),
             ('K-means Clustering', 'K-means ক্লাস্টারিং', 'Intermediate', 'lesson'),
             ('Hierarchical Clustering and DBSCAN',
              'হায়ারার্কিক্যাল ক্লাস্টারিং ও DBSCAN',
              'Advanced',
              'lesson'),
             ('Classification Metrics', 'ক্লাসিফিকেশন মেট্রিক', 'Intermediate', 'lesson'),
             ('Probability Calibration and Thresholds',
              'প্রবাবিলিটি ক্যালিব্রেশন ও থ্রেশহোল্ড',
              'Advanced',
              'lesson'),
             ('Bayesian Inference', 'বেইজিয়ান ইনফারেন্স', 'Advanced', 'lesson'),
             ('Causal Inference', 'কজাল ইনফারেন্স', 'Advanced', 'lesson')]},
 {'id': 'data-engineering',
  'title_en': 'Data Engineering Foundations',
  'title_bn': 'ডেটা ইঞ্জিনিয়ারিংয়ের ভিত্তি',
  'description_en': 'Learn how reliable analytical data is represented, modeled, transformed, tested, '
                    'orchestrated, and governed.',
  'description_bn': 'নির্ভরযোগ্য অ্যানালিটিক্যাল ডেটা কীভাবে উপস্থাপন, মডেল, ট্রান্সফর্ম, টেস্ট, '
                    'অর্কেস্ট্রেট ও গভর্ন করা হয় তা শিখুন।',
  'accent': 'teal',
  'icon': 'pipeline',
  'topics': [('Data Formats: CSV, JSON and Parquet',
              'ডেটা ফরম্যাট: CSV, JSON ও Parquet',
              'Beginner',
              'lesson'),
             ('Relational Data Modeling', 'রিলেশনাল ডেটা মডেলিং', 'Intermediate', 'lesson'),
             ('SQL for Analytics', 'অ্যানালিটিক্সের জন্য SQL', 'Intermediate', 'practice'),
             ('Normalization and Denormalization', 'নরমালাইজেশন ও ডিনরমালাইজেশন', 'Intermediate', 'lesson'),
             ('ETL and ELT', 'ETL ও ELT', 'Intermediate', 'lesson'),
             ('Batch and Streaming Data', 'ব্যাচ ও স্ট্রিমিং ডেটা', 'Intermediate', 'lesson'),
             ('Warehouse, Lake and Lakehouse', 'ডেটা ওয়্যারহাউস, লেক ও লেকহাউস', 'Intermediate', 'lesson'),
             ('Dimensional Modeling and Star Schemas',
              'ডাইমেনশনাল মডেলিং ও স্টার স্কিমা',
              'Advanced',
              'lesson'),
             ('Data Quality Testing', 'ডেটা কোয়ালিটি টেস্টিং', 'Intermediate', 'practice'),
             ('Pipeline Orchestration', 'পাইপলাইন অর্কেস্ট্রেশন', 'Advanced', 'lesson'),
             ('Data Lineage and Governance', 'ডেটা লিনিয়েজ ও গভর্ন্যান্স', 'Advanced', 'lesson'),
             ('Analytics Engineering and Semantic Layers',
              'অ্যানালিটিক্স ইঞ্জিনিয়ারিং ও সেমান্টিক লেয়ার',
              'Advanced',
              'lesson')]},
 {'id': 'advanced',
  'title_en': 'Advanced Statistical Methods',
  'title_bn': 'অ্যাডভান্সড স্ট্যাটিস্টিক্যাল মেথড',
  'description_en': 'Study experimental design, survival and multivariate methods, simulation, Markov '
                    'processes, and spatial reasoning.',
  'description_bn': 'এক্সপেরিমেন্টাল ডিজাইন, সারভাইভাল ও মাল্টিভ্যারিয়েট মেথড, সিমুলেশন, মার্কভ প্রসেস এবং '
                    'স্পেশাল বিশ্লেষণ শিখুন।',
  'accent': 'amber',
  'icon': 'atom',
  'topics': [('Experimental Design', 'এক্সপেরিমেন্টাল ডিজাইন', 'Advanced', 'lesson'),
             ('Factorial Designs', 'ফ্যাক্টোরিয়াল ডিজাইন', 'Advanced', 'lesson'),
             ('Repeated Measures', 'রিপিটেড মেজারস', 'Advanced', 'lesson'),
             ('Survival Analysis', 'সারভাইভাল অ্যানালাইসিস', 'Advanced', 'lesson'),
             ('Kaplan-Meier Estimation', 'ক্যাপলান-মায়ার এস্টিমেশন', 'Advanced', 'lesson'),
             ('Cox Proportional Hazards Model', 'কক্স প্রপোরশনাল হ্যাজার্ডস মডেল', 'Advanced', 'lesson'),
             ('Multivariate Normal Distribution',
              'মাল্টিভ্যারিয়েট নরমাল ডিস্ট্রিবিউশন',
              'Advanced',
              'lesson'),
             ('MANOVA', 'MANOVA', 'Advanced', 'lesson'),
             ('Factor Analysis', 'ফ্যাক্টর অ্যানালাইসিস', 'Advanced', 'lesson'),
             ('Monte Carlo Simulation', 'মন্টে কার্লো সিমুলেশন', 'Advanced', 'lab', 'monte-carlo-pi'),
             ('Markov Chains and MCMC', 'মার্কভ চেইন ও MCMC', 'Advanced', 'lesson'),
             ('Spatial Statistics', 'স্পেশাল স্ট্যাটিস্টিকস', 'Advanced', 'lesson')]}]

FORMULAS = {'mean-median-and-mode': ('Mean: x̄ = Σxᵢ / n', 'মিন: x̄ = Σxᵢ / n'),
 'weighted-geometric-and-harmonic-means': ('Weighted mean: x̄w = Σ(wᵢxᵢ) / Σwᵢ',
                                           'ওয়েটেড মিন: x̄w = Σ(wᵢxᵢ) / Σwᵢ'),
 'quantiles-and-percentiles': ('Linear-interpolation position: h = (n − 1)p',
                               'লিনিয়ার ইন্টারপোলেশন পজিশন: h = (n − 1)p'),
 'range-and-interquartile-range': ('Range = max − min; IQR = Q₃ − Q₁',
                                   'রেঞ্জ = সর্বোচ্চ − সর্বনিম্ন; IQR = Q₃ − Q₁'),
 'variance-and-standard-deviation': ('Sample variance: s² = Σ(xᵢ − x̄)² / (n − 1); s = √s²',
                                     'স্যাম্পল ভ্যারিয়েন্স: s² = Σ(xᵢ − x̄)² / (n − 1); s = √s²'),
 'coefficient-of-variation': ('CV = s / |x̄| × 100%', 'CV = s / |x̄| × 100%'),
 'probability-rules': ('P(A ∪ B) = P(A) + P(B) − P(A ∩ B)', 'P(A ∪ B) = P(A) + P(B) − P(A ∩ B)'),
 'conditional-probability': ('P(A | B) = P(A ∩ B) / P(B), when P(B) > 0',
                             'P(A | B) = P(A ∩ B) / P(B), যেখানে P(B) > 0'),
 'bayes-theorem': ('P(A | B) = P(B | A)P(A) / P(B)', 'P(A | B) = P(B | A)P(A) / P(B)'),
 'expected-value-and-variance': ('E[X] = ΣxP(X=x); Var(X) = E[(X − μ)²]',
                                 'E[X] = ΣxP(X=x); Var(X) = E[(X − μ)²]'),
 'bernoulli-and-binomial-distributions': ('P(X=k) = C(n,k)pᵏ(1−p)ⁿ⁻ᵏ', 'P(X=k) = C(n,k)pᵏ(1−p)ⁿ⁻ᵏ'),
 'poisson-distribution': ('P(X=k) = e⁻λ λᵏ / k!', 'P(X=k) = e⁻λ λᵏ / k!'),
 'normal-distribution': ('f(x)=1/(σ√(2π)) · exp(−(x−μ)²/(2σ²))', 'f(x)=1/(σ√(2π)) · exp(−(x−μ)²/(2σ²))'),
 'central-limit-theorem': ('For large n, (x̄ − μ)/(σ/√n) is approximately standard normal under regularity '
                           'conditions.',
                           'উপযুক্ত শর্তে বড় n-এর জন্য (x̄ − μ)/(σ/√n) প্রায় standard normal হয়।'),
 'confidence-intervals': ('Estimate ± critical value × standard error',
                          'Estimate ± critical value × standard error'),
 'one-sample-z-and-t-tests': ('t = (x̄ − μ₀)/(s/√n), df = n − 1', 't = (x̄ − μ₀)/(s/√n), df = n − 1'),
 'two-sample-t-test': ('Welch t = (x̄₁ − x̄₂)/√(s₁²/n₁ + s₂²/n₂)',
                       'Welch t = (x̄₁ − x̄₂)/√(s₁²/n₁ + s₂²/n₂)'),
 'chi-square-tests': ('χ² = Σ (Observed − Expected)² / Expected', 'χ² = Σ (Observed − Expected)² / Expected'),
 'analysis-of-variance': ('F = variance between groups / variance within groups',
                          'F = গ্রুপগুলোর মধ্যকার ভ্যারিয়েন্স / গ্রুপের ভেতরের ভ্যারিয়েন্স'),
 'covariance-and-correlation': ('r = cov(X,Y)/(sₓsᵧ)', 'r = cov(X,Y)/(sₓsᵧ)'),
 'simple-linear-regression': ('ŷ = b₀ + b₁x', 'ŷ = b₀ + b₁x'),
 'ordinary-least-squares': ('Choose coefficients that minimize Σ(yᵢ − ŷᵢ)²',
                            'যে coefficient-এ Σ(yᵢ − ŷᵢ)² সর্বনিম্ন হয় সেটি নির্বাচন করা হয়।'),
 'r-squared-and-adjusted-r-squared': ('R² = 1 − SSE/SST', 'R² = 1 − SSE/SST'),
 'logistic-regression': ('log(p/(1−p)) = β₀ + β₁x₁ + … + βₖxₖ', 'log(p/(1−p)) = β₀ + β₁x₁ + … + βₖxₖ'),
 'moving-averages-and-smoothing': ('SMAₜ = (yₜ + … + yₜ₋w₊₁)/w', 'SMAₜ = (yₜ + … + yₜ₋w₊₁)/w'),
 'bootstrap': ('Repeatedly resample n observations with replacement and summarize the resampled statistic.',
               'replacement সহ n observation বারবার resample করে statistic-এর distribution তৈরি করা হয়।'),
 'principal-component-analysis': ('Principal components are eigenvector directions of the '
                                  'covariance/correlation matrix.',
                                  'Principal component হলো covariance/correlation matrix-এর eigenvector '
                                  'direction।'),
 'k-means-clustering': ('Minimize within-cluster sum of squared distances to cluster centroids.',
                        'ক্লাস্টার centroid থেকে within-cluster squared distance-এর যোগফল সর্বনিম্ন করা হয়।'),
 'monte-carlo-simulation': ('Approximate an expectation or probability by repeated random sampling.',
                            'বারবার random sampling করে expectation বা probability আনুমানিক হিসাব করা হয়।'),
 'kaplan-meier-estimation': ('Ŝ(t) = ∏(1 − dᵢ/nᵢ) over event times tᵢ ≤ t',
                             'Ŝ(t) = ∏(1 − dᵢ/nᵢ), যেখানে event time tᵢ ≤ t'),
 'cox-proportional-hazards-model': ('h(t|x)=h₀(t)exp(βᵀx)', 'h(t|x)=h₀(t)exp(βᵀx)')}

MODULE_CONTEXT = {'foundations': ('survey and operational data', 'সার্ভে ও অপারেশনাল ডেটা'),
 'descriptive': ('sales, quality, and performance datasets', 'সেলস, কোয়ালিটি ও পারফরম্যান্স ডেটাসেট'),
 'probability': ('uncertain events, counts, and waiting times', 'অনিশ্চিত ঘটনা, কাউন্ট ও অপেক্ষার সময়'),
 'inference': ('samples, experiments, and evidence-based decisions',
               'স্যাম্পল, এক্সপেরিমেন্ট ও প্রমাণভিত্তিক সিদ্ধান্ত'),
 'regression': ('relationships and prediction problems', 'সম্পর্ক ও প্রেডিকশন সমস্যা'),
 'analytics': ('business performance and customer behavior', 'ব্যবসায়িক পারফরম্যান্স ও কাস্টমার আচরণ'),
 'data-science': ('machine-learning datasets and model evaluation', 'মেশিন লার্নিং ডেটাসেট ও মডেল মূল্যায়ন'),
 'data-engineering': ('reliable analytical data pipelines', 'নির্ভরযোগ্য অ্যানালিটিক্যাল ডেটা পাইপলাইন'),
 'advanced': ('research, experimentation, and complex data structures',
              'গবেষণা, এক্সপেরিমেন্ট ও জটিল ডেটা স্ট্রাকচার')}

COMMON_MISTAKES = {'foundations': ('Treating a convenient sample as representative; mixing measurement scales; ignoring how '
                 'data was generated.',
                 'সুবিধাজনক স্যাম্পলকে প্রতিনিধিত্বশীল ধরা, measurement scale গুলিয়ে ফেলা এবং ডেটা কীভাবে '
                 'তৈরি হয়েছে তা উপেক্ষা করা।'),
 'descriptive': ('Reporting only an average; hiding distribution shape; comparing spreads without '
                 'considering scale.',
                 'শুধু গড় রিপোর্ট করা, ডিস্ট্রিবিউশনের শেপ লুকিয়ে ফেলা এবং স্কেল বিবেচনা না করে বিস্তার '
                 'তুলনা করা।'),
 'probability': ('Confusing independence with mutual exclusivity; using the wrong distribution; interpreting '
                 'probability as certainty.',
                 'independence ও mutual exclusivity গুলিয়ে ফেলা, ভুল distribution ব্যবহার এবং probability-কে '
                 'নিশ্চয়তা হিসেবে ধরা।'),
 'inference': ('Equating non-significance with no effect; ignoring assumptions; focusing on p-values without '
               'effect size and uncertainty.',
               'non-significance-কে effect নেই বলা, assumption উপেক্ষা এবং effect size ও uncertainty বাদ '
               'দিয়ে শুধু p-value দেখা।'),
 'regression': ('Interpreting association as causation; extrapolating beyond observed data; ignoring '
                'residuals and leakage.',
                'association-কে causation বলা, observed range-এর বাইরে extrapolate করা এবং residual ও '
                'leakage উপেক্ষা করা।'),
 'analytics': ('Using unstable KPI definitions; changing experiment rules after seeing results; reporting '
               'charts without decisions.',
               'অস্থিতিশীল KPI definition ব্যবহার, ফল দেখার পর experiment rule বদলানো এবং সিদ্ধান্ত ছাড়া '
               'chart রিপোর্ট করা।'),
 'data-science': ('Fitting preprocessing on the full dataset; optimizing only one metric; ignoring class '
                  'imbalance and calibration.',
                  'পুরো dataset-এ preprocessing fit করা, শুধু একটি metric optimize এবং class imbalance ও '
                  'calibration উপেক্ষা করা।'),
 'data-engineering': ('Treating schema changes as harmless; skipping data tests; building pipelines without '
                      'ownership, lineage, or recovery plans.',
                      'schema change-কে harmless ধরা, data test বাদ দেওয়া এবং ownership, lineage বা recovery '
                      'plan ছাড়া pipeline তৈরি করা।'),
 'advanced': ('Using complex methods without checking identifiability, assumptions, censoring, dependence, '
              'or model diagnostics.',
              'identifiability, assumption, censoring, dependence বা model diagnostic যাচাই ছাড়া complex '
              'method ব্যবহার করা।')}
