"""Browser-based statistics labs retained in Data Learning Hub v2."""
from __future__ import annotations

TOOLS = [('summary-statistics',
  'Summary Statistics Lab',
  'সামারি স্ট্যাটিস্টিকস ল্যাব',
  'descriptive',
  'Calculate center, spread, quartiles, shape indicators, and a histogram from a numeric dataset.',
  'নিউমেরিক ডেটাসেট থেকে কেন্দ্র, বিস্তার, কোয়ার্টাইল, শেপ ইন্ডিকেটর ও হিস্টোগ্রাম হিসাব করুন।'),
 ('weighted-mean',
  'Weighted Mean Lab',
  'ওয়েটেড মিন ল্যাব',
  'descriptive',
  'Calculate weighted, geometric, and harmonic means with validation and interpretation.',
  'ভ্যালিডেশন ও ব্যাখ্যাসহ ওয়েটেড, জ্যামিতিক ও হারমোনিক গড় হিসাব করুন।'),
 ('z-score',
  'Z-score Calculator',
  'Z-score ক্যালকুলেটর',
  'descriptive',
  'Standardize a value and interpret its distance from the mean in standard-deviation units.',
  'একটি মানকে স্ট্যান্ডার্ডাইজ করুন এবং গড় থেকে স্ট্যান্ডার্ড ডেভিয়েশন এককে দূরত্ব ব্যাখ্যা করুন।'),
 ('percentile-quartile',
  'Percentile & Quartile Lab',
  'পার্সেন্টাইল ও কোয়ার্টাইল ল্যাব',
  'descriptive',
  'Find percentiles, quartiles, IQR, and percentile ranks using a documented interpolation rule.',
  'নির্ধারিত ইন্টারপোলেশন নিয়মে পার্সেন্টাইল, কোয়ার্টাইল, IQR ও পার্সেন্টাইল র\u200d্যাঙ্ক বের করুন।'),
 ('histogram',
  'Histogram Builder',
  'হিস্টোগ্রাম বিল্ডার',
  'descriptive',
  'Group numeric observations into bins and inspect the distribution shape.',
  'নিউমেরিক অবজারভেশনকে বিনে ভাগ করে ডিস্ট্রিবিউশনের শেপ দেখুন।'),
 ('box-plot',
  'Box Plot & Outlier Lab',
  'বক্স প্লট ও আউটলায়ার ল্যাব',
  'descriptive',
  'Compute the five-number summary and flag Tukey 1.5×IQR outliers.',
  'ফাইভ-নাম্বার সামারি হিসাব করুন এবং Tukey 1.5×IQR নিয়মে আউটলায়ার শনাক্ত করুন।'),
 ('pearson-correlation',
  'Pearson Correlation Lab',
  'পিয়ারসন কোরিলেশন ল্যাব',
  'regression',
  'Measure linear association between two numeric variables and inspect a scatter plot.',
  'দুইটি নিউমেরিক ভেরিয়েবলের লিনিয়ার সম্পর্ক পরিমাপ করুন এবং স্ক্যাটার প্লট দেখুন।'),
 ('linear-regression',
  'Simple Linear Regression Lab',
  'সিম্পল লিনিয়ার রিগ্রেশন ল্যাব',
  'regression',
  'Fit an ordinary least-squares line, inspect R² and residual error, and make a prediction.',
  'অর্ডিনারি লিস্ট-স্কয়ারস লাইন ফিট করুন, R² ও রেসিডুয়াল এরর দেখুন এবং প্রেডিকশন করুন।'),
 ('normal-probability',
  'Normal Probability Lab',
  'নরমাল প্রবাবিলিটি ল্যাব',
  'probability',
  'Calculate normal probabilities between bounds and visualize the density curve.',
  'দুই সীমার মধ্যবর্তী নরমাল প্রবাবিলিটি হিসাব করুন এবং ডেনসিটি কার্ভ দেখুন।'),
 ('binomial-probability',
  'Binomial Probability Lab',
  'বাইনোমিয়াল প্রবাবিলিটি ল্যাব',
  'probability',
  'Calculate exact, cumulative, and upper-tail binomial probabilities.',
  'বাইনোমিয়াল ডিস্ট্রিবিউশনের exact, cumulative ও upper-tail প্রবাবিলিটি হিসাব করুন।'),
 ('poisson-probability',
  'Poisson Probability Lab',
  'পয়সন প্রবাবিলিটি ল্যাব',
  'probability',
  'Calculate event-count probabilities from an expected rate.',
  'প্রত্যাশিত রেট থেকে event-count প্রবাবিলিটি হিসাব করুন।'),
 ('mean-confidence-interval',
  'Mean Confidence Interval Lab',
  'মিন কনফিডেন্স ইন্টারভ্যাল ল্যাব',
  'inference',
  'Estimate a population mean with a Student-t confidence interval.',
  'Student-t কনফিডেন্স ইন্টারভ্যাল দিয়ে পপুলেশন মিন অনুমান করুন।'),
 ('one-sample-t-test',
  'One-sample t Test Lab',
  'ওয়ান-স্যাম্পল t টেস্ট ল্যাব',
  'inference',
  'Test a sample mean against a hypothesized value and report the two-sided p-value.',
  'স্যাম্পল মিনকে একটি অনুমিত মানের সঙ্গে টেস্ট করুন এবং two-sided p-value দেখুন।'),
 ('two-sample-t-test',
  'Welch Two-sample t Test Lab',
  'Welch টু-স্যাম্পল t টেস্ট ল্যাব',
  'inference',
  'Compare two independent means without assuming equal variances.',
  'সমান ভ্যারিয়েন্স না ধরে দুইটি independent mean তুলনা করুন।'),
 ('chi-square-independence',
  'Chi-square Independence Lab',
  'কাই-স্কয়ার ইন্ডিপেনডেন্স ল্যাব',
  'inference',
  'Test association in a contingency table and inspect expected counts.',
  'কন্টিনজেন্সি টেবিলে সম্পর্ক টেস্ট করুন এবং expected count দেখুন।'),
 ('ab-test',
  'A/B Test for Proportions',
  'প্রপোরশনের A/B টেস্ট',
  'analytics',
  'Compare conversion rates with a pooled two-proportion z test and confidence interval.',
  'pooled two-proportion z test ও confidence interval দিয়ে conversion rate তুলনা করুন।'),
 ('clt-simulator',
  'Central Limit Theorem Simulator',
  'সেন্ট্রাল লিমিট থিওরেম সিমুলেটর',
  'probability',
  'Generate sample means and observe convergence toward an approximately normal sampling distribution.',
  'স্যাম্পল মিন তৈরি করে প্রায় নরমাল স্যাম্পলিং ডিস্ট্রিবিউশনের দিকে কনভার্জেন্স দেখুন।'),
 ('monte-carlo-pi',
  'Monte Carlo Pi Estimator',
  'মন্টে কার্লো Pi এস্টিমেটর',
  'advanced',
  'Estimate π by random sampling inside a unit square and inspect convergence.',
  'ইউনিট স্কয়ারে র\u200d্যান্ডম স্যাম্পলিং দিয়ে π অনুমান করুন এবং কনভার্জেন্স দেখুন।'),
 ('moving-average',
  'Moving Average Lab',
  'মুভিং এভারেজ ল্যাব',
  'analytics',
  'Smooth a time series with a configurable simple moving-average window.',
  'কনফিগারযোগ্য simple moving-average window দিয়ে টাইম সিরিজ স্মুথ করুন।'),
 ('sample-size-estimator',
  'Sample Size Estimator',
  'স্যাম্পল সাইজ এস্টিমেটর',
  'inference',
  'Estimate sample size for a proportion or mean at a chosen confidence and margin of error.',
  'নির্বাচিত confidence ও margin of error অনুযায়ী proportion বা mean-এর sample size অনুমান করুন।')]
